spring.application.name=university

# Database properties (Render.com)
spring.datasource.url=jdbc:postgresql://dpg-d7kso0t7vvec739n8a20-a.oregon-postgres.render.com:5432/university_db_u8q7
spring.datasource.username=university_admin
spring.datasource.password=beOrWb6MqBJOifpV27hgDFt0pO74MpXx
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion SSL obligatoria para Render
spring.datasource.properties.ssl=true
spring.datasource.properties.sslmode=require

# JPA/Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
